spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/iwattsdb
    username: iwatts
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # ou create-drop, none, etc. dependendo da sua estratégia
    show-sql: true # opcional, exibe as queries SQL no console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect